# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
